name = "SequentialCompression"
uuid = "a090a8c4-0549-4ee2-a6c2-f599d7ae654c"
authors = ["Átila Saraiva Quintela Soares"]
version = "0.1.0"

[deps]
ZfpCompression = "43441a71-1662-41c6-b8ea-40ed1525242b"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
